- name: create new ec2instance
  hosts: localhost
  connection: local
  vars:
   ami_id: "ami-09c813fb71547fc4f"
   sg_id: "sg-037afa32950284ea1"
   zone_id: "Z100089128WOYUCB7KSS2"
   domain_name: "awsdevops2025.fun"
   # instance we can give in -e
   instance:
   - mongodb
   - rabbitmq
   - redis
   - mysql  
   - catalogue
   - user
   - cart
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
     name: "{{ item }}"
     instance_type: t3.micro
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
     tags:
      name: "{{ item }}"
    loop: "{{ instance }}"

    register: ec2_output
  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
  - name: print private ip address
    ansible.builtin.debug: 
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_output.results }}"
  - name: print public ip address
    ansible.builtin.debug: 
      msg: "{{ item.instances[0].public_ip_address }}"
    loop: "{{ ec2_output.results }}"

  - name: crate route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"
  
      
