- name: commonappsetup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml
- name: commonappsetup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml


- name: systemsetup
  ansible.builtin.import_role:
    name: common
    tasks_from: system.setup.yaml